'use client';
import { useCallback,useEffect,useMemo,useState,useRef } from 'react';
import { Footprints,Plus,CalendarDays,ChartNoAxesColumn,House,Settings2,Moon,Dumbbell,Wine,ChevronRight,ChevronLeft,Leaf,Utensils,ShieldCheck,Link2,Check,RefreshCw,LogOut } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter } from '@/components/ui/alert-dialog';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { Toaster,toast } from 'sonner';
import { dateKey,isDate,summarize,recordSchema,Entry,Metric } from '@/lib/health';
const kinds={steps:{label:'걸음 수',Icon:Footprints,unit:'보',hint:'오늘 걸은 만큼'},exercise:{label:'운동',Icon:Dumbbell,unit:'분',hint:'움직인 시간을 남겨요'},sleep:{label:'수면',Icon:Moon,unit:'분',hint:'어젯밤 수면을 기록해요'},alcohol:{label:'음주',Icon:Wine,unit:'mL',hint:'마시지 않은 날도 기록해요'},meal:{label:'식단',Icon:Utensils,unit:'',hint:'오늘 먹은 음식을 남겨요'}};
const fmt=(n:number)=>n.toLocaleString('ko-KR');
const dayLabel=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'long'});
const minutes=(n:number)=>`${Math.floor(n/60)}시간${n%60?' '+n%60+'분':''}`;
const shift=(key:string,n:number)=>{const d=new Date(key+'T12:00:00');d.setDate(d.getDate()+n);return dateKey(d)};
function description(r:Entry){return r.metric==='sleep'?minutes(r.value):r.metric==='alcohol'?(r.value===0?'마시지 않았어요':`${r.kind} ${fmt(r.value)}mL`):r.metric==='meal'?r.note:`${fmt(r.value)}${kinds[r.metric].unit}${r.kind?' · '+r.kind:''}`;}
async function api(url:string,options?:RequestInit){const res=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options?.headers}});if(!res.ok){let message=res.status===401?'로그인이 만료됐어요. 새로고침 후 로그인해주세요.':'연결하지 못했어요. 다시 시도해주세요.';try{message=((await res.json()) as {error?:string}).error??message}catch{}throw new Error(message);}return res.json() as Promise<{records:Entry[];record:Entry;goal:number}>;}
export default function HealthApp({name='나',signedIn=false}:{name?:string,signedIn?:boolean}){
 const loadSequence=useRef(0); const [today,setToday]=useState('');const [month,setMonth]=useState('');const [selected,setSelected]=useState('');const [tab,setTab]=useState('today');const [rows,setRows]=useState<Entry[]>([]);const [goal,setGoal]=useState(8000);const [goalDraft,setGoalDraft]=useState('8000');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [period,setPeriod]=useState('week');const [chartDay,setChartDay]=useState('');const [editor,setEditor]=useState<{metric:Metric,date:string}|null>(null);const [value,setValue]=useState('');const [hours,setHours]=useState('');const [mins,setMins]=useState('');const [note,setNote]=useState('');const [kind,setKind]=useState('맥주');const [abv,setAbv]=useState('5');const [drank,setDrank]=useState('no');const [formError,setFormError]=useState('');const [confirmDelete,setConfirmDelete]=useState(false);const [connectOpen,setConnectOpen]=useState(false);
 useEffect(()=>{const sync=()=>{const key=dateKey(new Date());setToday(old=>{if(old&&old!==key){setMonth(key.slice(0,7));setSelected(key)}return key});};const key=dateKey(new Date());setToday(key);setSelected(key);setMonth(key.slice(0,7));const timer=setInterval(sync,60000);return()=>clearInterval(timer)},[]);
 const load=useCallback(async()=>{if(!month||!signedIn){setLoading(false);return;}const sequence=++loadSequence.current;setLoading(true);setError('');try{const first=month+'-01';const last=dateKey(new Date(Number(month.slice(0,4)),Number(month.slice(5)),0));const from=shift(first,-7);const [data,prefs,current]=await Promise.all([api(`/api/records?from=${from}&to=${last}`),api('/api/preferences'),today.slice(0,7)!==month?api(`/api/records?from=${today}&to=${today}`):Promise.resolve({records:[]})]);if(sequence!==loadSequence.current)return;setRows([...data.records,...current.records]);setGoal(prefs.goal);setGoalDraft(String(prefs.goal));}catch(e){if(sequence===loadSequence.current)setError((e as Error).message)}finally{if(sequence===loadSequence.current)setLoading(false)}},[month,today,signedIn]);
 useEffect(()=>{void load()},[load]);
 function openEditor(metric:Metric,date=today){if(!signedIn){window.location.href='/signin-with-chatgpt?return_to=/';return;}const r=rows.find(r=>r.date===date&&r.metric===metric);setEditor({metric,date});setValue(r?String(r.value):'');setHours(r?String(Math.floor(r.value/60)):'');setMins(r?String(r.value%60):'');setNote(r?.note??'');setKind(r?.kind||(metric==='alcohol'?'맥주':''));setAbv(String(r?.abv??5));setDrank(r&&r.value>0?'yes':'no');setFormError('');}
 function upsert(r:Entry){setRows(old=>[...old.filter(x=>!(x.date===r.date&&x.metric===r.metric)),r]);}
 async function save(){if(!editor)return;setFormError('');let number=Number(value);if(editor.metric==='sleep')number=Number(hours)*60+Number(mins);if(editor.metric==='meal'||(editor.metric==='alcohol'&&drank==='no'))number=0;if((editor.metric==='steps'||editor.metric==='exercise'||(editor.metric==='alcohol'&&drank==='yes'))&&!value.trim()){setFormError('숫자를 입력해주세요.');return;}if(editor.metric==='sleep'&&((!hours.trim()&&!mins.trim())||Number(mins)>=60||Number(mins)<0||Number(hours)<0||!Number.isInteger(Number(mins))||!Number.isInteger(Number(hours)))){setFormError('수면 시간을 확인해주세요. 분은 0~59까지 입력해주세요.');return;}if(editor.metric==='alcohol'&&drank==='yes'&&number<=0){setFormError('마신 양을 입력해주세요.');return;}const parsed=recordSchema.safeParse({...editor,value:number,note,kind:editor.metric==='alcohol'&&drank==='no'?'':kind,abv:editor.metric==='alcohol'&&drank==='yes'?Number(abv):0});if(!parsed.success){setFormError(parsed.error.issues[0].message);return;}setBusy(true);try{const data=await api('/api/records',{method:'PUT',body:JSON.stringify(parsed.data)});upsert(data.record);setEditor(null);toast.success('기록을 저장했어요.')}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function remove(){if(!editor)return;setBusy(true);try{await api(`/api/records?date=${editor.date}&metric=${editor.metric}`,{method:'DELETE'});setRows(old=>old.filter(r=>r.date!==editor.date||r.metric!==editor.metric));setConfirmDelete(false);setEditor(null);toast.success('기록을 삭제했어요.')}catch(e){setFormError((e as Error).message);setConfirmDelete(false)}finally{setBusy(false)}}
 async function saveGoal(e:React.FormEvent){e.preventDefault();setBusy(true);try{const data=await api('/api/preferences',{method:'PUT',body:JSON.stringify({goal:Number(goalDraft)})});setGoal(data.goal);toast.success('걸음 목표를 변경했어요.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 const current=rows.find(r=>r.date===today&&r.metric==='steps');const rate=current?Math.round(current.value/goal*100):0;
 const monthDays=useMemo(()=>{if(!month)return [];const n=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();return Array.from({length:n},(_,i)=>`${month}-${String(i+1).padStart(2,'0')}`)},[month]);
 const end=month===today.slice(0,7)?today:monthDays.at(-1)??today;const dates=period==='week'&&end?Array.from({length:7},(_,i)=>shift(end,i-6)):monthDays.filter(d=>d<=today);const summary=summarize(rows,dates,goal);const max=Math.max(goal,...rows.filter(r=>r.metric==='steps'&&dates.includes(r.date)).map(r=>r.value),1);const plotted=rows.find(r=>r.date===chartDay&&r.metric==='steps');
 function changeMonth(delta:number){const d=new Date(month+'-01T12:00:00');d.setMonth(d.getMonth()+delta);setMonth(dateKey(d).slice(0,7));setSelected(dateKey(d));setChartDay('');}
 const monthControl=<div className="month-control"><button aria-label="이전 달" onClick={()=>changeMonth(-1)}><ChevronLeft/></button><strong>{month.replace('-','년 ')}월</strong><button aria-label="다음 달" disabled={month>=today.slice(0,7)} onClick={()=>changeMonth(1)}><ChevronRight/></button></div>;
 const recordList=(date:string,includeSteps=false)=><section className="record-list">{(Object.keys(kinds) as Metric[]).filter(m=>includeSteps||m!=='steps').map(metric=>{const {Icon,label,hint}=kinds[metric];const r=rows.find(r=>r.date===date&&r.metric===metric);return <button disabled={loading||!!error||!date||date>today} className="record-row" key={metric} onClick={()=>openEditor(metric,date)}><span className={'icon-box '+metric}><Icon size={22}/></span><span className="record-copy"><strong>{label}</strong><small>{r?description(r):hint}</small></span>{r?<Check size={17} className="done"/>:<Plus size={18}/>}</button>})}</section>;
 useEffect(()=>{type ToolContext={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as Document&{modelContext?:ToolContext}).modelContext;if(!context)return;const controller=new AbortController();try{void Promise.resolve(context.registerTool({name:'open_health_record_editor',annotations:{readOnlyHint:false,untrustedContentHint:false},description:'날짜와 기록 종류를 선택해 입력창을 엽니다. 저장하지 않습니다.',inputSchema:{type:'object',properties:{date:{type:'string'},metric:{enum:Object.keys(kinds)}},required:['date','metric'],additionalProperties:false},execute:(input:{date:string,metric:Metric})=>{if(!input||!isDate(input.date)||!(input.metric in kinds)||input.date>today)throw new Error('올바른 날짜와 기록 종류가 필요합니다.');if(!signedIn||loading||error)throw new Error('로그인과 데이터 조회를 완료해주세요.');openEditor(input.metric,input.date);return {opened:true,date:input.date,metric:input.metric};}}, {signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[today,rows,signedIn,loading,error]);
 return <div className="phone-shell"><Toaster position="top-center" richColors/><header className="brand"><Leaf size={22}/><span>헬스 캘린더</span><ShieldCheck className="privacy-icon" size={20} aria-label="개인 기록"/></header><Tabs value={tab} onValueChange={v=>{setTab(v);window.scrollTo({top:0})}}><main>
 {!signedIn&&<div className="notice"><p>로그인하면 내 기록을 안전하게 저장할 수 있어요.</p><a href="/signin-with-chatgpt?return_to=/" target="_top">ChatGPT로 로그인 <ChevronRight size={16}/></a></div>}
 {error&&<div className="error" role="alert">{error}<button onClick={load}><RefreshCw size={16}/> 다시 시도</button></div>}
 <TabsContent value="today"><p className="eyebrow">오늘의 작은 실천</p><h1>가볍게, 한 걸음씩.</h1><p className="muted date">{today?dayLabel(today):'오늘의 건강을 기록해보세요.'}</p><section className="steps-hero"><div className="row"><span><Footprints size={20}/> 오늘 걸음</span><span className="badge">{current?.source==='health_connect'?'건강 앱 연동':'직접 입력'}</span></div><div className="step-number">{loading?'…':current?fmt(current.value):'—'} <small>보</small></div><Progress value={Math.min(rate,100)} className="step-progress" aria-label={`걸음 목표 ${rate}% 달성`}/><div className="row goal-line"><p>하루 목표 {fmt(goal)}보</p><p>{current?`${rate}%`:'아직 기록 전'}</p></div><button disabled={loading||!!error||!today} onClick={()=>openEditor('steps')} className="hero-action"><Plus size={18}/>{current?'걸음 수 수정':'걸음 수 기록'}</button></section><div className="section-head"><h2>오늘의 기록</h2><span>{rows.filter(r=>r.date===today&&r.metric!=='steps').length}/4 기록</span></div>{recordList(today)}<button className="connect-link" onClick={()=>setConnectOpen(true)}><Link2 size={17}/> 삼성헬스 연동 안내 <ChevronRight size={16}/></button></TabsContent>
 <TabsContent value="calendar"><p className="eyebrow">하루하루 쌓이는 기록</p><h1>나의 캘린더</h1>{monthControl}<section className="calendar-card"><div className="weekdays">{'일월화수목금토'.split('').map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{month&&Array.from({length:new Date(month+'-01T12:00:00').getDay()},(_,i)=><span key={'blank'+i}/>)}{monthDays.map(d=>{const recorded=rows.filter(r=>r.date===d);return <button key={d} disabled={d>today} className={(selected===d?'selected ':'')+(d===today?'is-today':'')} aria-label={`${dayLabel(d)}, 기록 ${recorded.length}개`} aria-pressed={selected===d} onClick={()=>setSelected(d)}><span>{Number(d.slice(-2))}</span><span className="dots">{recorded.slice(0,3).map(r=><i className={r.metric} key={r.metric}/>)}</span></button>})}</div></section><p className="calendar-help">날짜를 누르면 기록을 확인하고 수정할 수 있어요.</p><div className="section-head"><h2>{selected?dayLabel(selected):'날짜 선택'}</h2><button className="text-button" onClick={()=>{setMonth(today.slice(0,7));setSelected(today)}}>오늘</button></div>{recordList(selected,true)}</TabsContent>
 <TabsContent value="stats"><p className="eyebrow">숫자로 보는 나의 리듬</p><h1>꾸준함을 한눈에.</h1>{monthControl}<Tabs value={period} onValueChange={v=>{setPeriod(v);setChartDay('')}}><TabsList className="period-tabs"><TabsTrigger value="week">7일</TabsTrigger><TabsTrigger value="month">월간</TabsTrigger></TabsList></Tabs><section className="stat-card"><div className="row"><h2>일별 걸음 수</h2><Footprints size={21}/></div><div className="average">{summary.average===null?'—':fmt(summary.average)}<small> 보 / 기록일 평균</small></div><p className="muted stat-sub">{dates[0]?.slice(5).replace('-','/')} – {dates.at(-1)?.slice(5).replace('-','/')} · {summary.recorded}일 기록</p><div className="chart" role="group" aria-label="일별 걸음 수 그래프"><div className="goal-rule" style={{bottom:`${goal/max*100}%`}}><span>목표 {fmt(goal)}</span></div><div className="bars">{dates.map((d,i)=>{const r=rows.find(r=>r.date===d&&r.metric==='steps');return <button key={d} onClick={()=>setChartDay(d)} className={chartDay===d?'active':''} aria-label={`${d}: ${r?fmt(r.value)+'보':'미기록'}`}><i style={{height:r?`${Math.max(1,r.value/max*100)}%`:'3px',background:r?'':'#dce5e1'}}/><small>{period==='week'||i%5===0?Number(d.slice(-2)):''}</small></button>})}</div></div><p className="chart-caption">{chartDay?`${dayLabel(chartDay)} · ${plotted?fmt(plotted.value)+'보':'미기록'}`:'막대를 눌러 날짜별 걸음 수를 확인하세요.'}</p></section><div className="summary-grid"><section><span>목표 달성</span><strong>{summary.achieved}<small>일</small></strong><p>기록 {summary.recorded}일 중</p></section><section><span>평균 수면</span><strong className="sleep-number">{summary.sleep===null?'—':minutes(summary.sleep)}</strong><p>수면 기록일 기준</p></section><section><span>운동 시간</span><strong>{fmt(summary.exercise)}<small>분</small></strong><p>선택 기간 합계</p></section><section><span>음주 일수</span><strong>{summary.alcohol}<small>일</small></strong><p>음주 여부 기록 {summary.alcoholRecorded}일</p></section></div><p className="footnote">미기록은 0으로 계산하지 않아요. 음주는 마시지 않은 날도 기록해주세요.</p></TabsContent>
 <TabsContent value="settings"><p className="eyebrow">나에게 맞게</p><h1>내 설정</h1><section className="settings-card"><div className="row"><h2>내 계정</h2><ShieldCheck size={21}/></div><p className="account-name">{signedIn?name:'로그인 전'}</p><p className="muted">로그인한 계정의 기록만 표시됩니다.</p></section><section className="settings-card"><h2>하루 걸음 목표</h2><form onSubmit={saveGoal}><label className="sr-only" htmlFor="goal">하루 걸음 목표</label><div className="goal-form"><input id="goal" type="number" inputMode="numeric" min="1000" max="100000" step="1" required value={goalDraft} onChange={e=>setGoalDraft(e.target.value)}/><span>보</span><button className="primary compact" disabled={!signedIn||busy||loading||!!error}>저장</button></div></form></section><section className="settings-card"><div className="row"><h2>삼성헬스</h2><span className="status-chip">연결 전</span></div><p className="muted">갤럭시 핏의 걸음 수는 삼성헬스를 통해 가져올 수 있어요.</p><button className="secondary" onClick={()=>setConnectOpen(true)}>연동 방법 보기 <ChevronRight size={17}/></button></section><section className="settings-card"><h2>홈 화면에 추가</h2><p className="muted">휴대폰 브라우저 메뉴에서 ‘홈 화면에 추가’를 선택하면 더 편하게 열 수 있어요.</p></section>{signedIn&&<a className="signout" href="/signout-with-chatgpt?return_to=/" target="_top"><LogOut size={17}/> 로그아웃</a>}</TabsContent>
 </main><TabsList className="bottom-nav" aria-label="주 메뉴">{[{Icon:House,id:'today',label:'오늘'},{Icon:CalendarDays,id:'calendar',label:'캘린더'},{Icon:ChartNoAxesColumn,id:'stats',label:'통계'},{Icon:Settings2,id:'settings',label:'설정'}].map(({Icon,id,label})=><TabsTrigger key={id} value={id}><Icon/><span>{label}</span></TabsTrigger>)}</TabsList></Tabs>
 <Dialog open={!!editor} onOpenChange={open=>{if(!open&&!busy)setEditor(null)}}><DialogContent className="record-dialog" onOpenAutoFocus={e=>e.preventDefault()}><DialogTitle className="dialog-title">{editor?kinds[editor.metric].label:''} 기록</DialogTitle><DialogDescription>{editor?dayLabel(editor.date):''}</DialogDescription>{editor&&<form onSubmit={e=>{e.preventDefault();void save()}} className="entry-form"><fieldset disabled={busy}>{editor.metric==='alcohol'&&<><RadioGroup className="drink-choice" value={drank} onValueChange={setDrank} aria-label="음주 여부"><label><RadioGroupItem value="no"/> 안 마심</label><label><RadioGroupItem value="yes"/> 마심</label></RadioGroup>{drank==='yes'&&<><label>술 종류<Select value={kind} onValueChange={setKind}><SelectTrigger className="wide-select" aria-label="술 종류"><SelectValue/></SelectTrigger><SelectContent>{['맥주','소주','와인','막걸리','위스키','기타'].map(k=><SelectItem value={k} key={k}>{k}</SelectItem>)}</SelectContent></Select></label><label>도수 (%)<input type="number" inputMode="decimal" min="0" max="100" step="0.1" required value={abv} onChange={e=>setAbv(e.target.value)}/></label></>}{drank==='no'&&<p className="no-drink">오늘은 마시지 않은 날로 기록해요.</p>}</>}{editor.metric==='sleep'?<div className="sleep-fields"><label>시간<input type="number" inputMode="numeric" min="0" max="24" value={hours} placeholder="7" onChange={e=>setHours(e.target.value)}/></label><label>분<input type="number" inputMode="numeric" min="0" max="59" value={mins} placeholder="30" onChange={e=>setMins(e.target.value)}/></label></div>:editor.metric!=='meal'&&(editor.metric!=='alcohol'||drank==='yes')&&<label>{editor.metric==='alcohol'?'하루 총 마신 양':kinds[editor.metric].label} ({kinds[editor.metric].unit})<input type="number" inputMode="numeric" min={editor.metric==='alcohol'?1:0} max={{steps:200000,exercise:1440,alcohol:10000}[editor.metric as 'steps'|'exercise'|'alcohol']} step="1" required value={value} placeholder={editor.metric==='steps'?'예: 8420':editor.metric==='alcohol'?'예: 500':'예: 45'} onChange={e=>setValue(e.target.value)}/></label>}{editor.metric==='exercise'&&<label>운동 종류 (선택)<input value={kind} maxLength={60} placeholder="예: 걷기, 근력 운동" onChange={e=>setKind(e.target.value)}/></label>}<label>{editor.metric==='meal'?'먹은 음식':'메모 (선택)'}<textarea maxLength={1000} required={editor.metric==='meal'} value={note} placeholder={editor.metric==='meal'?'아침 · 점심 · 저녁을 자유롭게 남겨요.':'짧게 남기고 싶은 이야기가 있나요?'} onChange={e=>setNote(e.target.value)}/></label>{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="primary" type="submit">{busy?'저장 중…':'기록 저장'}</button>{rows.some(r=>r.metric===editor.metric&&r.date===editor.date)&&<button type="button" className="delete-button" onClick={()=>setConfirmDelete(true)}>이 기록 삭제</button>}</fieldset></form>}</DialogContent></Dialog>
 <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}><AlertDialogContent><AlertDialogTitle>이 기록을 삭제할까요?</AlertDialogTitle><AlertDialogDescription>선택한 날짜의 {editor?kinds[editor.metric].label:''} 기록만 삭제됩니다.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>취소</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void remove()}}>삭제</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={connectOpen} onOpenChange={setConnectOpen}><DialogContent className="record-dialog"><DialogTitle className="dialog-title">삼성헬스 연결 안내</DialogTitle><DialogDescription>갤럭시 핏 → 삼성헬스 → 헬스 커넥트</DialogDescription><div className="connection-info"><span className="status-chip">자동 연동 준비 중</span><p>웹 브라우저는 휴대폰의 건강 데이터를 직접 읽을 수 없어요. 자동으로 가져오려면 별도의 안드로이드 연동 앱 설치와 접근 허용이 필요합니다.</p><p>현재 버전은 직접 입력한 기록을 저장합니다. 자동 동기화는 아직 제공되지 않아요.</p><a href="https://developer.samsung.com/health/health-connect-faq.html" target="_blank" rel="noreferrer">삼성 공식 연동 안내 ↗</a></div></DialogContent></Dialog>
 </div>;
}



